---
:editor: vim -f -c '+/^\s*\n/' '+nohl' '+HardPencil'
:thread_by_subject: false
:edit_signature: false
:ask_for_from: true
:ask_for_to: true
:ask_for_cc: false
:ask_for_bcc: false
:ask_for_subject: true
:account_selector: true
:confirm_no_attachments: true
:confirm_top_posting: false
:jump_to_open_message: true
:discard_snippets_from_encrypted_messages: false
:load_more_threads_when_scrolling: true
:default_attachment_save_dir: "/home/benpote/attachments"
:sent_source: sup://sent
:archive_sent: true
:poll_interval: 150
:wrap_width: 0
:slip_rows: 0
:col_jump: 2
:stem_language: english
:sync_back_to_maildir: false
:continuous_scroll: true
:always_edit_async: false
:accounts:
  :default:
    :name: Ben Pote
    :email: ben.pote@gmail.com
    :sendmail: msmtp -t --read-envelope-from
    :signature: "/home/benpote/.signature"
    :gpgkey: ''
  :alice:
    :name: Alice Riot
    :email: alice.writes.wrongs@gmail.com
    :sendmail: msmtp -t --read-envelope-from
    :signature: "/home/benpote/.signature"
    :gpgkey: ''
  :hampshire:
    :name: Ben Pote
    :email: blp09@hampshire.edu
    :sendmail: msmtp -t --read-envelope-from
    :signature: "/home/benpote/.signature"
    :gpgkey: ''
  :riseup:
    :name: AR
    :email: axyridis@riseup.net
    :sendmail: msmtp -t --read-envelope-from
    :signature: "/home/benpote/.signature"
    :gpgkey: ''




