---
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/benpote/mail/personal/archive
  usual: true
  archived: false
  sync_back: true
  id: 1
  labels:
  - gmail
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/benpote/mail/riseup/INBOX/
  usual: true
  archived: false
  sync_back: true
  id: 4
  labels:
  - riseup
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/benpote/mail/riseup/LPC
  usual: true
  archived: false
  sync_back: true
  id: 5
  labels: []
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/benpote/mail/riseup/Drafts/
  usual: true
  archived: false
  sync_back: true
  id: 6
  labels: []
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/benpote/mail/hampshire/INBOX/
  usual: true
  archived: false
  sync_back: true
  id: 7
  labels:
  - hampshire
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/benpote/mail/hampshire/Sent
  usual: true
  archived: false
  sync_back: true
  id: 9
  labels:
  - hampshire
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/benpote/mail/hampshire/sent-mail
  usual: true
  archived: false
  sync_back: true
  id: 10
  labels:
  - hampshire
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/benpote/mail/hampshire/sent-mail-dec-2009/
  usual: true
  archived: false
  sync_back: true
  id: 11
  labels:
  - hampshire
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/benpote/mail/hampshire/sent-mail-mar-2010/
  usual: true
  archived: false
  sync_back: true
  id: 12
  labels:
  - hampshire
- !supmua.org,2006-10-01/Redwood/Maildir
  uri: maildir:/home/benpote/mail/riseup/Sent/
  usual: true
  archived: false
  sync_back: true
  id: 13
  labels: []
- !supmua.org,2006-10-01/Redwood/SentLoader {}
